on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v[0-9]+.[0-9]+' # Push events to matching release tags, i.e. v0.8

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: ./target/dtbook-schema_*_all.deb

